<a href="https://colab.research.google.com/github/ConfusedKlutz/Machine_Learning_Course/blob/main/Assignment1_102216039_NUMPY_MachineLearning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#reverse an array
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
rev_arr1 = np.flip(arr1)
print(rev_arr1)



[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
#flatten a numpy array #convert to 1D
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
flat_arr2 = arr2.flatten()
print(flat_arr2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [5]:
#compare the following numoy array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(np.array_equal(arr1,arr2))

True


In [6]:
from posixpath import normpath
#FIND THE MOST FREQUENT VALUE IN AN ARRAY
arr = np.array([0,1,3,2,2,3,4,5,2,1,2,1])
most_frequent_value_index = np.bincount(arr).argmax()
#find index of the most frequent value
most_frequent_value_index = np.where(arr == most_frequent_value_index)[0]
print(most_frequent_value_index)

[ 3  4  8 10]


In [7]:
#print sum of all elements in an array
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

#print the sum of all elements row-wise
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr,axis=1))

#print the sum of all elements column-wise
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr,axis=0))

array = np.array([range(10),range(10),range(10),range(10)])  #

summation = np.sum(array,axis=1).tolist()  #returns a list of the sums

print (summation)
print (type(summation))

15
[ 6 15 24]
[12 15 18]
[45, 45, 45, 45]
<class 'list'>


In [8]:
#for a matrix find the sum of diagonal elements
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.trace(arr))

# create numpy 2d-array
m = np.array([[1, 2],
              [2, 3]])
print("Printing the Original square array:\n",
      m)
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)
# printing eigen values
print("Printing the Eigen values of the given square array:\n",
      w)
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)


#print the determinant of a matrix
print(np.linalg.det(arr))

arr2 = np.array([[1,2],[3,4]])
print(np.linalg.det(arr2))
print(np.linalg.inv(arr2))

15
Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
0.0
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
#find the covariance between the matrices lists of list
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(np.cov(arr1,arr2))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [10]:
#multiply the following matrices
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[5,6]])
print(np.multiply(arr1,arr2))

[[ 4 10]
 [15 24]]


In [11]:
#For the matrices, x = np.array([[2,3,4],[3,2,9]]), y =np.array([[1,5,0], [5,10,3]]), find inner, outer, and cartesian product?
import numpy as np

# Matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner Product
inner_product = np.dot(x, y.T)

# Outer Product
outer_product = np.outer(x, y)

# Cartesian Product
# Creating a Cartesian product involves pairing each element from the flattened x with each element from the flattened y
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)  #flatten converts the 2d arrays into 1d arrays; then meshgrid works to convert the 1d array into a coordinate grid, which is basically the cartesian product


inner_product, outer_product, cartesian_product




(array([[17, 52],
        [13, 62]]),
 array([[ 2, 10,  0, 10, 20,  6],
        [ 3, 15,  0, 15, 30,  9],
        [ 4, 20,  0, 20, 40, 12],
        [ 3, 15,  0, 15, 30,  9],
        [ 2, 10,  0, 10, 20,  6],
        [ 9, 45,  0, 45, 90, 27]]),
 array([[ 2,  1],
        [ 2,  5],
        [ 2,  0],
        [ 2,  5],
        [ 2, 10],
        [ 2,  3],
        [ 3,  1],
        [ 3,  5],
        [ 3,  0],
        [ 3,  5],
        [ 3, 10],
        [ 3,  3],
        [ 4,  1],
        [ 4,  5],
        [ 4,  0],
        [ 4,  5],
        [ 4, 10],
        [ 4,  3],
        [ 3,  1],
        [ 3,  5],
        [ 3,  0],
        [ 3,  5],
        [ 3, 10],
        [ 3,  3],
        [ 2,  1],
        [ 2,  5],
        [ 2,  0],
        [ 2,  5],
        [ 2, 10],
        [ 2,  3],
        [ 9,  1],
        [ 9,  5],
        [ 9,  0],
        [ 9,  5],
        [ 9, 10],
        [ 9,  3]]))

# **What is np.meshgrid?**

np.meshgrid is a NumPy function that takes two arrays and creates a grid of coordinates from them. It essentially helps you pair every element of the first array with every element of the second array.
Simple Example

Let's say you have two lists of numbers:

    x = [1, 2]
    y = [3, 4]

You want to pair each number in x with each number in y. This would mean:

    Pair 1 from x with both 3 and 4 from y.
    Pair 2 from x with both 3 and 4 from y.

This gives you four pairs: (1, 3), (1, 4), (2, 3), and (2, 4)




In [12]:
np.meshgrid(x, y)

[array([[2, 3, 4, 3, 2, 9],
        [2, 3, 4, 3, 2, 9],
        [2, 3, 4, 3, 2, 9],
        [2, 3, 4, 3, 2, 9],
        [2, 3, 4, 3, 2, 9],
        [2, 3, 4, 3, 2, 9]]),
 array([[ 1,  1,  1,  1,  1,  1],
        [ 5,  5,  5,  5,  5,  5],
        [ 0,  0,  0,  0,  0,  0],
        [ 5,  5,  5,  5,  5,  5],
        [10, 10, 10, 10, 10, 10],
        [ 3,  3,  3,  3,  3,  3]])]

In [13]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
absolute_values = np.abs(array)
print(absolute_values)

# Flattened array percentiles
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])

# Percentiles for each column
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)

# Percentiles for each row
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("Percentiles (Flattened):", percentiles_flattened)
print("Percentiles (Columns):", percentiles_columns)
print("Percentiles (Rows):", percentiles_rows)

# Flattened array
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

# Each column
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

# Each row
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Flattened - Mean:", mean_flattened, "Median:", median_flattened, "STD:", std_flattened)
print("Columns - Mean:", mean_columns, "Median:", median_columns, "STD:", std_columns)
print("Rows - Mean:", mean_rows, "Median:", median_rows, "STD:", std_rows)



[[1 2 3]
 [4 5 6]]
Percentiles (Flattened): [-3.5 -0.5  2.5]
Percentiles (Columns): [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (Rows): [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened - Mean: -0.5 Median: -0.5 STD: 3.8622100754188224
Columns - Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] STD: [2.5 3.5 4.5]
Rows - Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] STD: [2.05480467 4.78423336]


In [14]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Floor:", floor_values)
print("Ceiling:", ceiling_values)
print("Truncated:", truncated_values)
print("Rounded:", rounded_values)


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [15]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print(sorted_array)

indices_sorted = np.argsort(array)
print(indices_sorted)

smallest_4 = np.sort(array)[:4]
print(smallest_4)

largest_5 = np.sort(array)[-5:]
print(largest_5)



[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [16]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
#print only the integer values
print(array[array == array.astype(int)])
#print only the float elements
print(array[array == array.astype(float)])

[1. 2. 3. 2.]
[1.  1.2 2.2 2.  3.  2. ]


In [26]:
import numpy as np
import cv2
from PIL import Image
import os

def img_to_array(path):
    # Open the image using OpenCV
    img = cv2.imread(path)

    # Check if the image is loaded properly
    if img is None:
        print("Error: Image not found or unable to load.")
        return None

    # Convert the RGB image to grayscale using OpenCV
    grayscale_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Save the grayscale image array to a text file
    np.savetxt("grayscale_image.txt", grayscale_image, fmt='%d')
    print("Grayscale image saved as grayscale_image.txt")

    # Return the original BGR image (OpenCV loads images as BGR)
    return img

# Store the path to the image in a variable
image_path = '/content/image.png'

# Call the function with the image path
img_array = img_to_array(image_path)

# Check if grayscale_image.txt was created and load it
if os.path.exists("grayscale_image.txt"):
    # Load the grayscale image from the text file
    grayscale_image = np.loadtxt("grayscale_image.txt")
    # Display the loaded grayscale image array
    print("Loaded Grayscale Image Array:")
    print(grayscale_image)

# Convert the OpenCV BGR image to RGB format (if you need the RGB channels)
if img_array is not None and img_array.ndim == 3:
    img_array_rgb = cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB)

    # Save each channel of the RGB image separately
    for i in range(3):
        np.savetxt(f"rgb_image_channel_{i}.txt", img_array_rgb[:, :, i], fmt='%d')
    print("RGB image channels saved as rgb_image_channel_0.txt, rgb_image_channel_1.txt, rgb_image_channel_2.txt")

    # Load each channel of the RGB image from their respective text files
    channel_0 = np.loadtxt("rgb_image_channel_0.txt")
    channel_1 = np.loadtxt("rgb_image_channel_1.txt")
    channel_2 = np.loadtxt("rgb_image_channel_2.txt")

    # Stack the channels to reconstruct the RGB image
    rgb_image = np.stack([channel_0, channel_1, channel_2], axis=-1)

    # Display the loaded RGB image array
    print("Loaded RGB Image Array:")
    print(rgb_image)

    # Optionally, you can convert the loaded RGB image to grayscale using numpy
    grayscale_image_np = np.dot(rgb_image[..., :3], [0.2989, 0.5870, 0.1140])

    print("Converted Grayscale Image Array (using numpy):")
    print(grayscale_image_np)


Grayscale image saved as grayscale_image.txt
Loaded Grayscale Image Array:
[[224. 224. 224. ... 255. 255. 255.]
 [224. 224. 224. ... 255. 255. 255.]
 [224. 224. 224. ... 255. 255. 255.]
 ...
 [ 21.  19.  21. ...  64.  61.  61.]
 [ 21.  19.  21. ...  64.  62.  62.]
 [ 21.  18.  21. ...  65.  62.  62.]]
RGB image channels saved as rgb_image_channel_0.txt, rgb_image_channel_1.txt, rgb_image_channel_2.txt
Loaded RGB Image Array:
[[[224. 224. 224.]
  [224. 224. 224.]
  [224. 224. 224.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[224. 224. 224.]
  [224. 224. 224.]
  [224. 224. 224.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[224. 224. 224.]
  [224. 224. 224.]
  [224. 224. 224.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[ 21.  21.  21.]
  [ 19.  19.  19.]
  [ 21.  21.  21.]
  ...
  [ 64.  64.  64.]
  [ 61.  61.  61.]
  [ 61.  61.  61.]]

 [[ 21.  21.  21.]
  [ 19.  19.  19.]
  [ 21.  21.  21.]
  ...
  [ 64.  64.  